FROM jenkins-test:production
MAINTAINER Simon Castillo <scastb@gmail.com>

# Setup application environment variables. Feel free to add any
# variable here that you might need in your development or staging
# environments.

# If you are using django-configurations you should make sure this is
# right.
ENV DJANGO_CONFIGURATION Development


# Install/do anything else you might need below.
